apiVersion: v1
kind: Service
metadata:
  name: svc2-node-port
  labels:
    app: httpd
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP
    name: httpd

