apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-dev
    labels:
        app: myapp
        type: fornt-end
spec:
  template:
    metadata:
       name: myapp
       labels:
          app: myapp
          type: fornt-end
    spec: 
        containers:
        - name: nginx-containers
          image: nginx
replicas: 3
selector:
    matchLables:
        type: fornt-end
