#kubectl get deployments.apps py-app -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-11-20T10:12:13Z"
  generation: 1
  labels:
    app: py-app
  name: py-app
  namespace: default
  resourceVersion: "2797"
  uid: a3e818fc-1792-4cbb-94f2-bb1713f72609
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: py-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: py-app
    spec:
      containers:
      - image: amirn88/my-python_new
        imagePullPolicy: Always
        name: my-python-new-s8hcz
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-11-20T10:12:20Z"
    lastUpdateTime: "2024-11-20T10:12:20Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-11-20T10:12:13Z"
    lastUpdateTime: "2024-11-20T10:12:20Z"
    message: ReplicaSet "py-app-684774d46c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

